### ISSUE TITLE
As the project owner, I want a cool name for this project, so that people will find it appealing.

### ISSUE THREAD

**Issue by jbrysch** [jbrysch/HARP-Initial#6]
Validate that I have an acronym which is awesome to say and encompasses what I am doing on this project.

**Comment by jbrysch** [comment]
Come up with a project name
Spread the news
Update documentation

**Comment by gloyd** [comment]
What about Project Awesome. Or just call it JOEY

**Comment by jbrysch** [comment]
Smart Integrated Node Environment (SINE)
