### ISSUE TITLE
As a developer, I want to have a RESTful service on the master server, so that I can record information to our database.

### ISSUE THREAD

**Issue by jbrysch** [jbrysch/HARP-Initial#7]
Validate that a REST service is up and running on the master server.
Validate that the REST service has a GET,POST,DELETE operation for nodes/clients.
Validate that everything regarding this REST service is documented.

**Comment by jbrysch** [comment]
Download and configure NodeJs on master server.
Expose endpoint to clients
Test endpoints from clients
Document

**Comment by gloyd** [comment]
:+1:
